// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "../ui.h"

void ui_landing_page_screen_init(void)
{
ui_landing_page = lv_obj_create(NULL);
lv_obj_clear_flag( ui_landing_page, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Buttonpanel = lv_obj_create(ui_landing_page);
lv_obj_set_width( ui_Buttonpanel, 320);
lv_obj_set_height( ui_Buttonpanel, 180);
lv_obj_set_x( ui_Buttonpanel, 0 );
lv_obj_set_y( ui_Buttonpanel, 150 );
lv_obj_set_align( ui_Buttonpanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Buttonpanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Buttonpanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Buttonpanel, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttonpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttonpanel, lv_color_hex(0x00B2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttonpanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Buttonpanel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Buttonpanel, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_Buttonpanel, 150, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_top_panel = lv_obj_create(ui_landing_page);
lv_obj_set_width( ui_top_panel, 320);
lv_obj_set_height( ui_top_panel, 60);
lv_obj_set_x( ui_top_panel, 0 );
lv_obj_set_y( ui_top_panel, -210 );
lv_obj_set_align( ui_top_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_top_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_top_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_top_panel, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_top_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_top_panel, lv_color_hex(0x00B2FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_top_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_top_panel, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_top_panel, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_top_panel, 150, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date_placeholder = lv_label_create(ui_top_panel);
lv_obj_set_width( ui_date_placeholder, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_date_placeholder, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_date_placeholder, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_date_placeholder,"Mon 5 Jun");
lv_obj_set_style_text_color(ui_date_placeholder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_date_placeholder, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_battery_placeholder = lv_label_create(ui_top_panel);
lv_obj_set_width( ui_battery_placeholder, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_battery_placeholder, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_battery_placeholder, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_battery_placeholder,"95%");
lv_obj_set_style_text_color(ui_battery_placeholder, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_battery_placeholder, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_passcode_button = lv_btn_create(ui_landing_page);
lv_obj_set_width( ui_passcode_button, 120);
lv_obj_set_height( ui_passcode_button, 40);
lv_obj_set_x( ui_passcode_button, -75 );
lv_obj_set_y( ui_passcode_button, 165 );
lv_obj_set_align( ui_passcode_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_passcode_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_passcode_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_passcode_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_passcode_button, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_passcode_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_passcode_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_passcode_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_passcode_button_label = lv_label_create(ui_passcode_button);
lv_obj_set_width( ui_passcode_button_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_passcode_button_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_passcode_button_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_passcode_button_label,"Enter passcode");

ui_delivery_button = lv_btn_create(ui_landing_page);
lv_obj_set_width( ui_delivery_button, 120);
lv_obj_set_height( ui_delivery_button, 40);
lv_obj_set_x( ui_delivery_button, 75 );
lv_obj_set_y( ui_delivery_button, 165 );
lv_obj_set_align( ui_delivery_button, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_delivery_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_delivery_button, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_delivery_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_delivery_button, lv_color_hex(0x00B0FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_delivery_button, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_delivery_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_delivery_button, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_delivery_button_label = lv_label_create(ui_delivery_button);
lv_obj_set_width( ui_delivery_button_label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_delivery_button_label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_delivery_button_label, LV_ALIGN_CENTER );
lv_label_set_text(ui_delivery_button_label,"Delivery");

ui_cam_panel = lv_obj_create(ui_landing_page);
lv_obj_set_width( ui_cam_panel, 320);
lv_obj_set_height( ui_cam_panel, 240);
lv_obj_set_x( ui_cam_panel, 0 );
lv_obj_set_y( ui_cam_panel, -60 );
lv_obj_set_align( ui_cam_panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_cam_panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_cam_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_cam_panel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_cam_panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_cam_panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_cam_panel);
lv_img_set_src(ui_Image1, &ui_img_hej_png);
lv_obj_set_width( ui_Image1, 320);
lv_obj_set_height( ui_Image1, 240);
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_delivery_button, ui_event_delivery_button, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_landing_page, ui_event_landing_page, LV_EVENT_ALL, NULL);

}
