// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_landing_page
void ui_landing_page_screen_init(void);
lv_obj_t *ui_landing_page;
lv_obj_t *ui_cam_panel;
lv_obj_t *ui_Image2;
lv_obj_t *ui_Buttonpanel;
lv_obj_t *ui_top_panel;
lv_obj_t *ui_date_placeholder;
lv_obj_t *ui_battery_placeholder;
lv_obj_t *ui_passcode_button;
lv_obj_t *ui_passcode_button_label;
lv_obj_t *ui_delivery_button;
lv_obj_t *ui_delivery_button_label;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_landing_page_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_landing_page);
}
