// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#ifndef _KLOKKE_UI_H
#define _KLOKKE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_landing_page
void ui_landing_page_screen_init(void);
extern lv_obj_t *ui_landing_page;
extern lv_obj_t *ui_cam_panel;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Buttonpanel;
extern lv_obj_t *ui_top_panel;
extern lv_obj_t *ui_date_placeholder;
extern lv_obj_t *ui_battery_placeholder;
extern lv_obj_t *ui_passcode_button;
extern lv_obj_t *ui_passcode_button_label;
extern lv_obj_t *ui_delivery_button;
extern lv_obj_t *ui_delivery_button_label;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_hej_png);   // assets/hej.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
