// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "ui.h"
#include <ArduinoWebsockets.h>
#include <TFT_eSPI.h>
#include <TJpg_Decoder.h>

const char* ssid = "ESP32-THAT-PROJECT";
const char* password = "California";

using namespace websockets;
WebsocketsServer server;
WebsocketsClient client;

// Button2 rButton = Button2(RIGHT_BUTTON_PIN);
// Button2 lButton = Button2(LEFT_BUTTON_PIN);
TFT_eSPI tft1 = TFT_eSPI();

bool tft_output(int16_t x, int16_t y, uint16_t w, uint16_t h, uint16_t* bitmap){
	if ( y >= tft1.height() ) return 0;
	tft1.pushImage(x, y, w, h, bitmap);
  return 1;
}

int xPos = 0;
int yPos = 120;

void beginServer(lv_event_t * e)
{
	TJpgDec.setJpgScale(1);
	TJpgDec.setCallback(tft_output);

	WiFi.softAP(ssid, password,1,true);

  	IPAddress IP = WiFi.softAPIP();
  	server.listen(8888);

}

void updateImg(lv_event_t * e)
{
	if(server.poll()){
		client = server.accept();
		}

	if(client.available()){
		client.poll();
		
		WebsocketsMessage msg = client.readBlocking();
		uint32_t t = millis();
		
		TJpgDec.drawJpg(xPos, yPos, (const uint8_t*)msg.c_str(), msg.length());
		
		t = millis() - t;
		Serial.print(t); Serial.println(" ms");
	}

}

void stopServer(lv_event_t * e)
{
	// Your code here
}
