// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: remote

#include "ui.h"
extern bool showImage;
extern bool addPasscodeBool;
extern bool removePasscodeBool;
extern bool unlockBool;
extern char * passcode;
extern bool stopBuzzer;

void beginStream(lv_event_t * e)
{
	showImage = true;
}

void stopStream(lv_event_t * e)
{
	showImage = false;
}

void unlock(lv_event_t * e)
{
	unlockBool = true;
}

void addPasscode(lv_event_t * e)
{
	passcode = lv_textarea_get_text(ui_add_passcode_text_area);
	if(passcode != NULL && strlen(passcode) > 3){
		_ui_screen_change( ui_adding_passcode_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
		addPasscodeBool = true;



	}
}

void removePasscode(lv_event_t * e)
{
	passcode = lv_textarea_get_text(ui_remove_passcode_text_area);
	if(passcode != NULL && strlen(passcode) > 3){
		_ui_screen_change( ui_removing_passcode_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
		removePasscodeBool = true;
	}
	
}

void stopNotification(lv_event_t * e)
{
	stopBuzzer = true;
}
