// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: remote

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_landing_page
void ui_landing_page_screen_init(void);
void ui_event_landing_page( lv_event_t * e);
lv_obj_t *ui_landing_page;
lv_obj_t *ui_Buttonpanel;
lv_obj_t *ui_DateBatteryPanelMain;
lv_obj_t *ui_date_placeholder;
lv_obj_t *ui_battery_placeholder;
void ui_event_passcode_control_button( lv_event_t * e);
lv_obj_t *ui_passcode_control_button;
lv_obj_t *ui_passcode_control_label;
void ui_event_Unlock_button( lv_event_t * e);
lv_obj_t *ui_Unlock_button;
lv_obj_t *ui_Unlock_button_label;
lv_obj_t *ui_cam_panel;
lv_obj_t *ui_Image1;

// SCREEN: ui_add_passcode_screen
void ui_add_passcode_screen_screen_init(void);
lv_obj_t *ui_add_passcode_screen;
lv_obj_t *ui_add_passcode_go_back_button_pane;
void ui_event_add_passcode_go_back_button( lv_event_t * e);
lv_obj_t *ui_add_passcode_go_back_button;
lv_obj_t *ui_add_passcode_go_back_button_labe;
lv_obj_t *ui_DateBatteryPanelPassword;
lv_obj_t *ui_date_placeholder1;
lv_obj_t *ui_battery_placeholder1;
void ui_event_add_passcode_keyboard( lv_event_t * e);
lv_obj_t *ui_add_passcode_keyboard;
void ui_event_add_passcode_text_area( lv_event_t * e);
lv_obj_t *ui_add_passcode_text_area;

// SCREEN: ui_Unlocking
void ui_Unlocking_screen_init(void);
void ui_event_Unlocking( lv_event_t * e);
lv_obj_t *ui_Unlocking;
lv_obj_t *ui_unlocking_screen_spinner;
lv_obj_t *ui_Label1;

// SCREEN: ui_passcode_control_screen
void ui_passcode_control_screen_screen_init(void);
lv_obj_t *ui_passcode_control_screen;
lv_obj_t *ui_passcode_control_label1;
lv_obj_t *ui_go_back_button_panel;
void ui_event_passcode_control_go_back_button( lv_event_t * e);
lv_obj_t *ui_passcode_control_go_back_button;
lv_obj_t *ui_passcode_control_go_back_but_lab;
lv_obj_t *ui_DateBatteryPanelPassword1;
lv_obj_t *ui_date_placeholder2;
lv_obj_t *ui_battery_placeholder2;
lv_obj_t *ui_Buttonpanel3;
void ui_event_add_passcode_button( lv_event_t * e);
lv_obj_t *ui_add_passcode_button;
lv_obj_t *ui_add_passcode_button_label;
void ui_event_remove_passcode_button( lv_event_t * e);
lv_obj_t *ui_remove_passcode_button;
lv_obj_t *ui_remove_passcode_button_label;

// SCREEN: ui_adding_passcode_screen
void ui_adding_passcode_screen_screen_init(void);
void ui_event_adding_passcode_screen( lv_event_t * e);
lv_obj_t *ui_adding_passcode_screen;
lv_obj_t *ui_adding_passcode_spinner;
lv_obj_t *ui_Adding_Passcode_label;

// SCREEN: ui_removing_passcode_screen
void ui_removing_passcode_screen_screen_init(void);
void ui_event_removing_passcode_screen( lv_event_t * e);
lv_obj_t *ui_removing_passcode_screen;
lv_obj_t *ui_remove_passcode_spinner;
lv_obj_t *ui_remove_Passcode_label;

// SCREEN: ui_remove_passcode_screen
void ui_remove_passcode_screen_screen_init(void);
lv_obj_t *ui_remove_passcode_screen;
lv_obj_t *ui_remove_passcode;
void ui_event_remove_passcode_go_back_button( lv_event_t * e);
lv_obj_t *ui_remove_passcode_go_back_button;
lv_obj_t *ui_remove_passcode_go_back_button_l;
lv_obj_t *ui_DateBatteryPanelPassword2;
lv_obj_t *ui_date_placeholder3;
lv_obj_t *ui_battery_placeholder3;
void ui_event_remove_passcode_keyboard( lv_event_t * e);
lv_obj_t *ui_remove_passcode_keyboard;
void ui_event_remove_passcode_text_area( lv_event_t * e);
lv_obj_t *ui_remove_passcode_text_area;

// SCREEN: ui_notification_screen
void ui_notification_screen_screen_init(void);
void ui_event_notification_screen( lv_event_t * e);
lv_obj_t *ui_notification_screen;
lv_obj_t *ui_notification_labl;
lv_obj_t *ui_Image3;
void ui_event_remove_passcode_go_back_button1( lv_event_t * e);
lv_obj_t *ui_remove_passcode_go_back_button1;
lv_obj_t *ui_remove_passcode_go_back_button_l;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_1515648418[1] = {&ui_img_15611405};
const lv_img_dsc_t *ui_imgset_861137800[4] = {&ui_img_1114486417, &ui_img_32757238, &ui_img_1048971941, &ui_img_386404288};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_landing_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      beginStream( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOADED) {
      stopStream( e );
}
}
void ui_event_passcode_control_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_passcode_control_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
}
}
void ui_event_Unlock_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      unlock( e );
      _ui_screen_change( ui_Unlocking, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0);
}
}
void ui_event_add_passcode_go_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_passcode_control_screen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0);
}
}
void ui_event_add_passcode_keyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_adding_passcode_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
}
}
void ui_event_add_passcode_text_area( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      addPasscode( e );
}
}
void ui_event_Unlocking( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( ui_landing_page, LV_SCR_LOAD_ANIM_NONE, 500, 5000);
}
}
void ui_event_passcode_control_go_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_landing_page, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0);
}
}
void ui_event_add_passcode_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_add_passcode_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
}
}
void ui_event_remove_passcode_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_remove_passcode_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
}
}
void ui_event_adding_passcode_screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( ui_landing_page, LV_SCR_LOAD_ANIM_NONE, 500, 5000);
}
}
void ui_event_removing_passcode_screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( ui_landing_page, LV_SCR_LOAD_ANIM_NONE, 500, 5000);
}
}
void ui_event_remove_passcode_go_back_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_passcode_control_screen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0);
}
}
void ui_event_remove_passcode_keyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_get_act());
      _ui_screen_change( ui_removing_passcode_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
}
}
void ui_event_remove_passcode_text_area( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      removePasscode( e );
}
}
void ui_event_notification_screen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( ui_landing_page, LV_SCR_LOAD_ANIM_NONE, 500, 5000);
}
}
void ui_event_remove_passcode_go_back_button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_passcode_control_screen, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0);
      stopNotification( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_landing_page_screen_init();
ui_add_passcode_screen_screen_init();
ui_Unlocking_screen_init();
ui_passcode_control_screen_screen_init();
ui_adding_passcode_screen_screen_init();
ui_removing_passcode_screen_screen_init();
ui_remove_passcode_screen_screen_init();
ui_notification_screen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_landing_page);
}
