// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: remote

#include "ui.h"

void beginStream(lv_event_t * e)
{
	// Your code here
}

void stopStream(lv_event_t * e)
{
	// Your code here
}

void unlock(lv_event_t * e)
{
	// Your code here
}

void addPasscode(lv_event_t * e)
{
	// Your code here
}

void removePasscode(lv_event_t * e)
{
	// Your code here
}
