// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_landing_page
void ui_landing_page_screen_init(void);
void ui_event_landing_page( lv_event_t * e);
lv_obj_t *ui_landing_page;
lv_obj_t *ui_Buttonpanel;
lv_obj_t *ui_DateBatteryPanelMain;
lv_obj_t *ui_date_placeholder;
lv_obj_t *ui_battery_placeholder;
void ui_event_button1( lv_event_t * e);
lv_obj_t *ui_button1;
lv_obj_t *ui_passcode_button_label1;
void ui_event_delivery_button( lv_event_t * e);
lv_obj_t *ui_delivery_button;
lv_obj_t *ui_delivery_button_label;
lv_obj_t *ui_cam_panel;
lv_obj_t *ui_Image1;

// SCREEN: ui_PasswordScreen
void ui_PasswordScreen_screen_init(void);
lv_obj_t *ui_PasswordScreen;
lv_obj_t *ui_Buttonpanel1;
void ui_event_delivery_button1( lv_event_t * e);
lv_obj_t *ui_delivery_button1;
lv_obj_t *ui_Go_Back;
lv_obj_t *ui_DateBatteryPanelPassword;
lv_obj_t *ui_date_placeholder1;
lv_obj_t *ui_battery_placeholder1;
lv_obj_t *ui_PasswordKeyboard;
lv_obj_t *ui_TextArea1;

// SCREEN: ui_Unlocking
void ui_Unlocking_screen_init(void);
void ui_event_Unlocking( lv_event_t * e);
lv_obj_t *ui_Unlocking;
lv_obj_t *ui_Spinner2;
lv_obj_t *ui_Label1;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_landing_page( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      beginServer( e );
      updateImg( e );
}
if ( event_code == LV_EVENT_SCREEN_UNLOADED) {
      stopServer( e );
}
}
void ui_event_button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_PasswordScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 500, 0);
}
}
void ui_event_delivery_button( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      updateImg( e );
}
}
void ui_event_delivery_button1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( ui_landing_page, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0);
}
}
void ui_event_Unlocking( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      _ui_screen_change( ui_landing_page, LV_SCR_LOAD_ANIM_FADE_ON, 500, 5000);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_landing_page_screen_init();
ui_PasswordScreen_screen_init();
ui_Unlocking_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_landing_page);
}
