// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "ui.h"

extern bool showImage;
extern bool sendPasscode;
extern char * passcode;
extern bool accessGranted;

void beginServer(lv_event_t * e)
{
	showImage = true;
}

void stopServer(lv_event_t * e)
{
	showImage = false;

}

void unlock(lv_event_t * e)
{
	passcode = lv_textarea_get_text(ui_passwordArea);
	if(passcode != NULL && strlen(passcode) > 3){
		_ui_screen_change( ui_Unlocking, LV_SCR_LOAD_ANIM_NONE, 500, 0);
		sendPasscode = true;
	}

}


void unlocking(lv_event_t * e)
{
	if(accessGranted){
		_ui_screen_change( ui_unlocked_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
		sendPasscode = false;
		accessGranted = false;
	} else {
		_ui_screen_change( ui_not_unlocked_screen, LV_SCR_LOAD_ANIM_NONE, 500, 0);
		sendPasscode = false;
	}
}
