// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "ui.h"

void beginServer(lv_event_t * e)
{
	// Your code here
}

void updateImg(lv_event_t * e)
{
	// Your code here
}

void stopServer(lv_event_t * e)
{
	// Your code here
}
