// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "ui.h"

extern bool showImage;
extern bool sendPassword;
extern char * password;


void beginServer(lv_event_t * e)
{
	showImage = true;
}

void stopServer(lv_event_t * e)
{
	showImage = false;
}

void unlock(lv_event_t * e)
{
	password = lv_textarea_get_text(ui_passwordArea);
	if(password != NULL && strlen(password) > 3){
		sendPassword = true;
		_ui_screen_change( ui_Unlocking, LV_SCR_LOAD_ANIM_NONE, 500, 0);

	}

}
