// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "../ui.h"

void ui_Unlocking_screen_init(void)
{
ui_Unlocking = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Unlocking, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Unlocking, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Unlocking, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Unlocking, lv_color_hex(0x313031), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Unlocking, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_Spinner2 = lv_spinner_create(ui_Unlocking,1000,90);
lv_obj_set_width( ui_Spinner2, 80);
lv_obj_set_height( ui_Spinner2, 80);
lv_obj_set_x( ui_Spinner2, 0 );
lv_obj_set_y( ui_Spinner2, -50 );
lv_obj_set_align( ui_Spinner2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Spinner2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

lv_obj_set_style_arc_color(ui_Spinner2, lv_color_hex(0x0079FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Spinner2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Unlocking);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 0 );
lv_obj_set_y( ui_Label1, 65 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Unlocking...");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Unlocking, ui_event_Unlocking, LV_EVENT_ALL, NULL);

}
