// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: doorbell

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Keyboard1 = lv_keyboard_create(ui_Screen2);
lv_keyboard_set_mode(ui_Keyboard1,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Keyboard1, 300);
lv_obj_set_height( ui_Keyboard1, 296);
lv_obj_set_x( ui_Keyboard1, -1 );
lv_obj_set_y( ui_Keyboard1, 70 );
lv_obj_set_align( ui_Keyboard1, LV_ALIGN_CENTER );

ui_TextArea1 = lv_textarea_create(ui_Screen2);
lv_obj_set_width( ui_TextArea1, 270);
lv_obj_set_height( ui_TextArea1, 47);
lv_obj_set_x( ui_TextArea1, -5 );
lv_obj_set_y( ui_TextArea1, -119 );
lv_obj_set_align( ui_TextArea1, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_TextArea1,"Placeholder...");

lv_keyboard_set_textarea(ui_Keyboard1,ui_TextArea1);

}
