// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: klokke

#include "../ui.h"

void ui_PasswordScreen_screen_init(void)
{
ui_PasswordScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PasswordScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PasswordScreen, lv_color_hex(0x898889), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PasswordScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Buttonpanel1 = lv_obj_create(ui_PasswordScreen);
lv_obj_set_width( ui_Buttonpanel1, 320);
lv_obj_set_height( ui_Buttonpanel1, 79);
lv_obj_set_align( ui_Buttonpanel1, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Buttonpanel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Buttonpanel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Buttonpanel1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Buttonpanel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Buttonpanel1, lv_color_hex(0xFF4136), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Buttonpanel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Buttonpanel1, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Buttonpanel1, LV_BORDER_SIDE_TOP, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_delivery_button1 = lv_btn_create(ui_PasswordScreen);
lv_obj_set_width( ui_delivery_button1, 120);
lv_obj_set_height( ui_delivery_button1, 40);
lv_obj_set_x( ui_delivery_button1, 0 );
lv_obj_set_y( ui_delivery_button1, 200 );
lv_obj_set_align( ui_delivery_button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_delivery_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_delivery_button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_delivery_button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_delivery_button1, lv_color_hex(0x007BFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_delivery_button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_delivery_button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_delivery_button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Go_Back = lv_label_create(ui_delivery_button1);
lv_obj_set_width( ui_Go_Back, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Go_Back, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Go_Back, LV_ALIGN_CENTER );
lv_label_set_text(ui_Go_Back,"Go Back");

ui_DateBatteryPanelPassword = lv_obj_create(ui_PasswordScreen);
lv_obj_set_width( ui_DateBatteryPanelPassword, 320);
lv_obj_set_height( ui_DateBatteryPanelPassword, 60);
lv_obj_set_x( ui_DateBatteryPanelPassword, 0 );
lv_obj_set_y( ui_DateBatteryPanelPassword, -210 );
lv_obj_set_align( ui_DateBatteryPanelPassword, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_DateBatteryPanelPassword, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_DateBatteryPanelPassword, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DateBatteryPanelPassword, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DateBatteryPanelPassword, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DateBatteryPanelPassword, lv_color_hex(0xFF4136), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DateBatteryPanelPassword, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DateBatteryPanelPassword, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_DateBatteryPanelPassword, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_date_placeholder1 = lv_label_create(ui_DateBatteryPanelPassword);
lv_obj_set_width( ui_date_placeholder1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_date_placeholder1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_date_placeholder1, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_date_placeholder1,"Mon 19 Jun");
lv_obj_set_style_text_color(ui_date_placeholder1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_date_placeholder1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PasswordKeyboard = lv_keyboard_create(ui_PasswordScreen);
lv_keyboard_set_mode(ui_PasswordKeyboard,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_PasswordKeyboard, 300);
lv_obj_set_height( ui_PasswordKeyboard, 229);
lv_obj_set_x( ui_PasswordKeyboard, 0 );
lv_obj_set_y( ui_PasswordKeyboard, -90 );
lv_obj_set_align( ui_PasswordKeyboard, LV_ALIGN_BOTTOM_MID );

ui_passwordArea = lv_textarea_create(ui_PasswordScreen);
lv_obj_set_width( ui_passwordArea, 283);
lv_obj_set_height( ui_passwordArea, LV_SIZE_CONTENT);   /// 131
lv_obj_set_x( ui_passwordArea, 0 );
lv_obj_set_y( ui_passwordArea, -126 );
lv_obj_set_align( ui_passwordArea, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_passwordArea,4);
lv_textarea_set_placeholder_text(ui_passwordArea,"Enter code...");
lv_textarea_set_one_line(ui_passwordArea,true);
lv_textarea_set_password_mode(ui_passwordArea, true);
lv_obj_set_style_text_font(ui_passwordArea, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_align(ui_passwordArea, LV_TEXT_ALIGN_LEFT, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_passwordArea, &lv_font_montserrat_30, LV_PART_TEXTAREA_PLACEHOLDER| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_delivery_button1, ui_event_delivery_button1, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_PasswordKeyboard,ui_passwordArea);
lv_obj_add_event_cb(ui_PasswordKeyboard, ui_event_PasswordKeyboard, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_passwordArea, ui_event_passwordArea, LV_EVENT_ALL, NULL);

}
