// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: remote

#include "../ui.h"

void ui_notification_screen_screen_init(void)
{
ui_notification_screen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_notification_screen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_notification_screen, lv_color_hex(0x313031), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_notification_screen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_notification_screen, lv_color_hex(0x313031), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_notification_screen, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_notification_labl = lv_label_create(ui_notification_screen);
lv_obj_set_width( ui_notification_labl, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_notification_labl, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_notification_labl, 0 );
lv_obj_set_y( ui_notification_labl, 85 );
lv_obj_set_align( ui_notification_labl, LV_ALIGN_CENTER );
lv_label_set_text(ui_notification_labl,"Someone is at the door");
lv_obj_set_style_text_color(ui_notification_labl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_notification_labl, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_notification_labl, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_notification_screen);
lv_img_set_src(ui_Image3, &ui_img_1999303404);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, 0 );
lv_obj_set_y( ui_Image3, -20 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_remove_passcode_go_back_button1 = lv_btn_create(ui_notification_screen);
lv_obj_set_width( ui_remove_passcode_go_back_button1, 120);
lv_obj_set_height( ui_remove_passcode_go_back_button1, 40);
lv_obj_set_x( ui_remove_passcode_go_back_button1, 0 );
lv_obj_set_y( ui_remove_passcode_go_back_button1, 199 );
lv_obj_set_align( ui_remove_passcode_go_back_button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_remove_passcode_go_back_button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_remove_passcode_go_back_button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_remove_passcode_go_back_button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_remove_passcode_go_back_button1, lv_color_hex(0x007BFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_remove_passcode_go_back_button1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_remove_passcode_go_back_button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_remove_passcode_go_back_button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_remove_passcode_go_back_button_l = lv_label_create(ui_remove_passcode_go_back_button1);
lv_obj_set_width( ui_remove_passcode_go_back_button_l, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_remove_passcode_go_back_button_l, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_remove_passcode_go_back_button_l, LV_ALIGN_CENTER );
lv_label_set_text(ui_remove_passcode_go_back_button_l,"Go Back");

lv_obj_add_event_cb(ui_remove_passcode_go_back_button1, ui_event_remove_passcode_go_back_button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_notification_screen, ui_event_notification_screen, LV_EVENT_ALL, NULL);

}
